sudo: required
language: bash
services:
  - docker
before_script:
  - docker build -t ${KBC_APP_REPOSITORY} .
script: 
  - docker run ${KBC_APP_REPOSITORY}
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
notifications:
  email: false
  slack:
    secure: lH5ACE6qSlPuqwJY7rvql2OWs/9mzAZXrvuaimVGeLXa5mX5QQtWP2lMAj6UEN9pos9SrcNoTvxMwk0huaIEmXQ62RWePl38aJqoY5I8W61H7s0Eu7gdGSAj1txG2Oz5fh6pBfK9Nb+8DoC8r2TzjrK9VMz+YZAsLsPveKBztme9M7qooPM/yQ0kNht1rIYlC/h2Vw8/p2gJsbewj/CIUbnqbrjKvAZMNXeBJ1Lwmdm54dG395xIXEsCsZ/8uPl4yYYSDgK9KUc5iAiCuCN8+MAVNoygcDWw2B0ICK+EwcdLS57urT1tDYcC6HxmplJy6U7Wmz7BvqoDzKuo33MRfnu9sp8jg/e2G8P4v15PdVgreqG8sEZJZJMXpxi1LEwZJwTDCH6Nh0zmW11+CSTRFn4IwcIrSpNF7i7leNURIIbkkzqB736Aitb2NHgmmTxyc8qVwvYW/CsdY1FwhahJMenrdLZHQbz2zlf7VC9c7iEIYD8OC2OTKoRoNZ/jxNwKTJLdlPjAu2U22hksGPuqsSp6AqNePV7AV16hfAYew18K7iVHLte5EEVtZZ/9Ucrd5+oyfJnovTDwruJ0R9xZ/vEUnOS6UEy+NvbqRkzbCQjdguqstV0T/ZdvSap/gUdOEQiAJyL8xjBck3hzR5hm7gdM0EePIG6g2T0EFMUBOpU=
